[package]
name = "parsey"
description = "A simple parser-generator framework."
version = "0.1.2"
edition = "2021"
keywords = ["parser", "no_std"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/parsey/latest/parsey/"
repository = "https://github.com/swolfenden9/parsey"

[dependencies]
